services:
  - type: web
    name: ohip-catalog
    runtime: python
    buildCommand: ./build.sh
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: REQUIRE_LOGIN
        value: "False"
      - key: PYTHON_VERSION
        value: "3.11.7"
